n_conv_layers: 3
n_affine_layers: 1
n_affine_neurons: 500
filter_params: {"n": [36, 64, 128], "strides": 1, "size": 4, "padding": 'SAME'}
pool_params: {"strides": 2, "size": 2, "padding": 'SAME'}
keep_prob: 0.6
learning_rate: 1e-3
