n_conv_layers: 2
n_affine_layers: 2
n_affine_neurons: 120
filter_params: {"n": 64, "strides": 2, "size": 4, "padding": 'VALID'}
pool_params: {"strides": 2, "size": 2}
keep_prob: 0.5
learning_rate: 1e-4
